name: Lint code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    uses: stegripe/workflows/.github/workflows/pnpm-lint.yaml@70f2b51880ed314ac9a98c2cd2de6582668c4a9a # main
    secrets: inherit