name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    uses: stegripe/workflows/.github/workflows/pnpm-publish.yaml@fcfd6bae08c7afa0a213fae4584a8667f0214688 # main
    secrets: inherit