name: Publish to NPM and GitHub registry

on:
  release:
    types: [created]

jobs:
  publish:
    uses: stegripe/workflows/.github/workflows/pnpm-publish.yaml@70f2b51880ed314ac9a98c2cd2de6582668c4a9a # main
    secrets: inherit